TARGET = XK-1
APP_NAME =
XCC_FLAGS = -O3 -g
XCC_MAP_FLAGS = -report

USED_MODULES = module_dct_jpeg module_huffman_jpeg


#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
