TARGET = XK-1A
APP_NAME =
USED_MODULES = module_fft_simple module_window
XCC_FLAGS = -O3
VERBOSE = 0


#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
