TARGET = XK-1
APP_NAME =
XCC_FLAGS = -O3 -fllvm -lm -Xmapper --map -Xmapper /tmp/mapfile
USED_MODULES = module_fft_simple module_window

# Use the main Makefile from module_xmos_common
include ../../xcommon/module_xcommon/build/Makefile.common
